# Generated by Django 4.2.29 on 2026-03-20 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_telegramlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional + prefix).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон'),
        ),
    ]
