# Generated by Django 4.2.29 on 2026-03-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationcontract',
            options={'ordering': ['-created_at', '-start_date']},
        ),
    ]
