# Generated by Django 4.2.29 on 2026-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0002_alter_accommodationcontract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationcontract',
            options={'ordering': ['-created_at', '-start_date'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='roomassignment',
            options={'ordering': ['-start_date'], 'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.AlterModelOptions(
            name='stayrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись проживания', 'verbose_name_plural': 'Записи проживания'},
        ),
        migrations.AlterField(
            model_name='accommodationcontract',
            name='contract_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='accommodationcontract',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='accommodationcontract',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='accommodationcontract',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('expired', 'Истёк'), ('terminated', 'Расторгнут')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активное'), ('completed', 'Завершено'), ('transferred', 'Переведено')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='stayrecord',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заселение'),
        ),
        migrations.AlterField(
            model_name='stayrecord',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='stayrecord',
            name='reason',
            field=models.CharField(choices=[('initial_check_in', 'Заселение'), ('transfer', 'Перевод'), ('eviction', 'Выселение'), ('graduation', 'Выпуск'), ('temporary_leave', 'Временный выезд'), ('return', 'Возвращение')], max_length=30),
        ),
    ]
