# Generated by Django 4.2.29 on 2026-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0003_alter_accommodationcontract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='beds_purchased',
            field=models.PositiveIntegerField(default=1, verbose_name='Мест куплено'),
        ),
    ]
