# Generated by Django 4.2.29 on 2026-04-16 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0006_alter_residentdocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Вход'), ('out', 'Выход')], max_length=3, verbose_name='Направление')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время события')),
                ('device_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Устройство')),
                ('card_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер карты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='residents.resident', verbose_name='Жилец')),
            ],
            options={
                'verbose_name': 'Событие доступа',
                'verbose_name_plural': 'События доступа',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resident', '-timestamp'], name='access_cont_residen_d1c525_idx'), models.Index(fields=['direction', '-timestamp'], name='access_cont_directi_199cd9_idx')],
            },
        ),
    ]
