# Generated by Django 4.2.29 on 2026-03-13 06:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional + prefix).', regex='^\\+?\\d{10,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('university_id', models.CharField(max_length=50, verbose_name='Student ID')),
                ('faculty', models.CharField(blank=True, max_length=150, verbose_name='Faculty')),
                ('course', models.PositiveIntegerField(blank=True, null=True, verbose_name='Course')),
                ('photo', models.ImageField(blank=True, upload_to='residents/photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('evicted', 'Evicted'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='organizations.organization')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('organization', 'university_id')},
            },
        ),
        migrations.CreateModel(
            name='ResidentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('student_id', 'Student ID'), ('contract', 'Contract'), ('medical', 'Medical certificate'), ('other', 'Other')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='residents/documents/')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residents.resident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], default='other', max_length=20)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional + prefix).', regex='^\\+?\\d{10,15}$')])),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='residents.resident')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
