# Generated by Django 4.2.29 on 2026-03-17 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_resident_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='residentdocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', 'ID-карта'), ('passport', 'Паспорт'), ('drivers_license', 'Водительское удостоверение')], max_length=20),
        ),
    ]
