# Generated by Django 4.2.29 on 2026-03-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_faculty_alter_residentdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('evicted', 'Evicted'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
