# Generated by Django 4.2.29 on 2026-03-19 07:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_alter_resident_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['full_name'], 'verbose_name': 'Опекун', 'verbose_name_plural': 'Опекуны'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['full_name'], 'verbose_name': 'Жилец', 'verbose_name_plural': 'Жильцы'},
        ),
        migrations.AlterModelOptions(
            name='residentdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='is_emergency_contact',
            field=models.BooleanField(default=False, verbose_name='Экстренный контакт'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional + prefix).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(choices=[('father', 'Отец'), ('mother', 'Мать'), ('sibling', 'Брат/Сестра'), ('uncle', 'Дядя'), ('aunt', 'Тётя'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Родство'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='residents.resident', verbose_name='Жилец'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional + prefix).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, upload_to='residents/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активный'), ('evicted', 'Выселен'), ('graduated', 'Выпустился'), ('suspended', 'Приостановлен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='university_id',
            field=models.CharField(max_length=50, verbose_name='Студ. билет'),
        ),
        migrations.AlterField(
            model_name='residentdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='residentdocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', 'ID-карта'), ('passport', 'Паспорт'), ('drivers_license', 'Водительское удостоверение')], max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='residentdocument',
            name='file',
            field=models.FileField(upload_to='residents/documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='residentdocument',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residents.resident', verbose_name='Жилец'),
        ),
    ]
