# Generated by Django 4.2.29 on 2026-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_faculty_options_alter_guardian_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentdocument',
            name='file',
            field=models.FileField(blank=True, upload_to='residents/documents/', verbose_name='Файл'),
        ),
    ]
