# Generated by Django 4.2 on 2026-09-06 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0002_default_university'),
        ('inventory', '0005_building_university_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupancy', '0004_roomassignment_beds_purchased'),
        ('residents', '0008_university_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('academic_year', models.CharField(help_text='2026/2027', max_length=9, verbose_name='Учебный год')),
                ('start_date', models.DateField(verbose_name='Начало проживания')),
                ('end_date', models.DateField(verbose_name='Окончание проживания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('enforce', models.BooleanField(default=True, verbose_name='Проверять правила при заселении админом')),
                ('buildings_sequential', models.BooleanField(default=False, help_text='Следующий корпус открывается, когда в предыдущих нет свободных мест для этого студента', verbose_name='Корпуса заполняются по очереди')),
                ('floors_sequential', models.BooleanField(default=False, verbose_name='Этажи заполняются по очереди')),
                ('hold_hours', models.PositiveIntegerField(default=24, verbose_name='Срок брони, часов')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Кампания заселения',
                'verbose_name_plural': 'Кампании заселения',
                'ordering': ['-start_date', 'name'],
                'unique_together': {('university', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='PlacementRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.JSONField(blank=True, default=list, verbose_name='Курсы')),
                ('faculties', models.JSONField(blank=True, default=list, verbose_name='Факультеты')),
                ('foreign_policy', models.CharField(choices=[('any', 'Все студенты'), ('only_foreign', 'Только иностранные'), ('only_local', 'Только местные')], default='any', max_length=20, verbose_name='Иностранцы')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_rules', to='inventory.building')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='admission.admissioncampaign')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_rules', to='inventory.floor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_rules', to='inventory.room')),
            ],
            options={
                'verbose_name': 'Ограничение по местам',
                'verbose_name_plural': 'Ограничения по местам',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.JSONField(blank=True, default=list, verbose_name='Курсы')),
                ('faculties', models.JSONField(blank=True, default=list, verbose_name='Факультеты')),
                ('foreign_policy', models.CharField(choices=[('any', 'Все студенты'), ('only_foreign', 'Только иностранные'), ('only_local', 'Только местные')], default='any', max_length=20, verbose_name='Иностранцы')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('opens_at', models.DateTimeField(verbose_name='Открывается')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрывается')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='admission.admissioncampaign')),
            ],
            options={
                'verbose_name': 'Окно доступа',
                'verbose_name_plural': 'Окна доступа',
                'ordering': ['opens_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beds', models.PositiveIntegerField(default=1, verbose_name='Мест')),
                ('status', models.CharField(choices=[('reserved', 'Забронировано'), ('confirmed', 'Подтверждено'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='reserved', max_length=20)),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('override_reason', models.TextField(blank=True, verbose_name='Причина обхода правил')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='occupancy.roomassignment')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='admission.admissioncampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='residents.resident')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inventory.room')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 заполняется первым', verbose_name='Очередь')),
                ('floor_direction', models.CharField(choices=[('asc', 'Снизу вверх (1 → N)'), ('desc', 'Сверху вниз (N → 1)'), ('custom', 'Свой порядок')], default='asc', max_length=10, verbose_name='Порядок этажей')),
                ('floor_order', models.JSONField(blank=True, default=list, help_text='Номера этажей по очереди', verbose_name='Свой порядок этажей')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_orders', to='inventory.building')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_orders', to='admission.admissioncampaign')),
            ],
            options={
                'verbose_name': 'Очередь корпуса',
                'verbose_name_plural': 'Очередь корпусов',
                'ordering': ['priority'],
                'unique_together': {('campaign', 'building')},
            },
        ),
    ]
