# Generated by Django 4.2.29 on 2026-03-13 05:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('gender_policy', models.CharField(choices=[('male_only', 'Male only'), ('female_only', 'Female only'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='Floor number')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='inventory.building')),
            ],
            options={
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20, verbose_name='Room number')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacity')),
                ('current_occupancy', models.PositiveIntegerField(default=0, verbose_name='Current occupancy')),
                ('gender_policy', models.CharField(choices=[('male_only', 'Male only'), ('female_only', 'Female only'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], default='available', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monthly price')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory.floor')),
            ],
            options={
                'ordering': ['floor__building__name', 'floor__number', 'room_number'],
                'unique_together': {('floor', 'room_number')},
            },
        ),
    ]
