# Generated by Django 4.2.29 on 2026-03-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='building',
            name='organization',
        ),
    ]
