# Generated by Django 4.2.29 on 2026-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_building_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['building', 'number'], 'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor__building__name', 'floor__number', 'room_number'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='building',
            name='gender_policy',
            field=models.CharField(choices=[('male_only', 'Только мужчины'), ('female_only', 'Только женщины'), ('mixed', 'Смешанный')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер этажа'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=4, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущая загрузка'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='gender_policy',
            field=models.CharField(choices=[('male_only', 'Только мужчины'), ('female_only', 'Только женщины'), ('mixed', 'Смешанный')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена в месяц'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Есть места'), ('full', 'Занята'), ('maintenance', 'Ремонт'), ('closed', 'Закрыта')], default='available', max_length=20),
        ),
    ]
