# Generated by Django 4.2.29 on 2026-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_tariffplan_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['period_year', 'period_month'], 'verbose_name': 'Начисление', 'verbose_name_plural': 'Начисления'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-start_date'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'verbose_name': 'Распределение', 'verbose_name_plural': 'Распределения'},
        ),
        migrations.AlterModelOptions(
            name='tariffplan',
            options={'ordering': ['name'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='due_date',
            field=models.DateField(verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='period_month',
            field=models.PositiveIntegerField(verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='period_year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('partially_paid', 'Частично оплачено'), ('paid', 'Оплачено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('bank_transfer', 'Банковский перевод')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('cancelled', 'Отменена')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Ежемесячно'), ('semester', 'Семестр'), ('yearly', 'Годовой')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
