# Generated by Django 4.2.29 on 2026-04-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_building_options_alter_floor_options_and_more'),
        ('billing', '0003_alter_charge_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['period_year', 'period_month', 'start_day'], 'verbose_name': 'Начисление', 'verbose_name_plural': 'Начисления'},
        ),
        migrations.AlterUniqueTogether(
            name='charge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='charge',
            name='days_charged',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней'),
        ),
        migrations.AddField(
            model_name='charge',
            name='end_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='По день'),
        ),
        migrations.AddField(
            model_name='charge',
            name='is_prorated',
            field=models.BooleanField(default=False, verbose_name='Пропорциональный'),
        ),
        migrations.AddField(
            model_name='charge',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='inventory.room', verbose_name='Комната'),
        ),
        migrations.AddField(
            model_name='charge',
            name='start_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='С дня'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('resident', 'period_month', 'period_year', 'room'), name='unique_charge_per_resident_room_month'),
        ),
    ]
